### ISSUE TITLE
VCO--3340 is slightly out of tune.

### ISSUE THREAD

**Issue by carljohanlinell** [LabSevenDevVCVRack/LabSeven_VCVRack_modules#1]
Hi. Great module, very nice sound, great feature set.

Only thing, the oscillator seems to be slightly out of tune. With nothing at the V/OCT jack, the oscillator sits at 528.6Hz, where I assume it was supposed to sit at 523.251Hz, an octave above middle C.

**Comment by messiaenpsp** [comment]
Thanks for the information! I think I know what the problem is. Consider this

![grafik](https://user-images.githubusercontent.com/47555213/52644629-7a8a9d00-2edf-11e9-91a3-8ac51e9286e1.png)

Comment out

pitch *= 1.0+0.02*((double) rand() / (RAND_MAX));

It should be precise then.

The bug is that all values of ((double) rand() / (RAND_MAX)) are positive with the mean at 0.5. It should be ((double) rand() / (RAND_MAX) - 0.5) in order to get a mean of 0. These things happen when you work at a late hour...

A quick calculation tells me that if this is indeed the error, the VCO should sit at 528,48351 Hz +- some jitter. I think that this is the problem.

Thank you for making me aware of this! I'll fix it quickly and provide an update that also contains some minor performance improvements.

**Comment by messiaenpsp** [comment]
Ok, just tested it and seems fine now. Repo is updated. Thanks a lot!

**Comment by carljohanlinell** [comment]
Cool!

Remember to throw a new build up :)

**Comment by LabSevenDevVCVRack** [comment]
I will, as soon as some other improvements have been made!
