### ISSUE TITLE
Update to Rack v1

### ISSUE THREAD

**Issue by pgatt** [LabSevenDevVCVRack/LabSeven_VCVRack_modules#2]
Hi there, I was wondering if there was any chance you would update your VCV Rack module to be compatible with VCV Rack v1?

**Comment by LabSevenDevVCVRack** [comment]
Hi! Thanks for your interest! There are several plugins that need to be ported - some of them have not been released yet. Unfortunately, due to a lack of time, I can not do that right now.
I also think that the VCO3340 module for Rack v 1.x should support polyphony.
But as I was saying, at the moment I can not predict when I will have time to do that.

**Comment by pgatt** [comment]
There is a developer Netboy who has done some work porting some other older plugins up to v1 comparability. Would you like a hand?

**Comment by LabSevenDevVCVRack** [comment]
Sure, help is always welcome :-) Thanks for the suggestion!

Maybe we can start with a simple port to v1 without changes to the algorithms. 

Then, when I have time, it would be nice to add polyphony, maybe replace sinc interpolation by simple oversampling+decimation, try SIMD instructions for better performance and add frequency dependent amplitude scaling in order to 'perfectly' emulate the SH sound.

**Comment by netboy3** [comment]
Hi,

I've just completed a V1 migration of this module. [Pull Request](https://github.com/LabSevenDevVCVRack/LabSeven_VCVRack_modules/pull/3) was posted with the modifications for LabSeven to review and hopefully merge. Following are builds for the community to test out. Feedback is appreciated.

Linux: [LabSeven-1.0.0-lin.zip](https://github.com/LabSevenDevVCVRack/LabSeven_VCVRack_modules/files/4077404/LabSeven-1.0.0-lin.zip)
Mac: [LabSeven-1.0.0-mac.zip](https://github.com/LabSevenDevVCVRack/LabSeven_VCVRack_modules/files/4077405/LabSeven-1.0.0-mac.zip)
Windows: [LabSeven-1.0.0-win.zip](https://github.com/LabSevenDevVCVRack/LabSeven_VCVRack_modules/files/4077406/LabSeven-1.0.0-win.zip)

**Comment by prospectumdev** [comment]
Wow, thank you so much!!! I'll give it a try and get back to you!

**Comment by LabSevenDevVCVRack** [comment]
Great job, seems to be perfect - we are now at version 1.1.6.1! Again, thank you very much for your effort!!!

**Comment by netboy3** [comment]
> Great job, seems to be perfect - we are now at version 1.1.6.1! Again, thank you very much for your effort!!!

You are very welcome. Happy to see yet another classic  module back in VCV and on my "wall" of module migrations :smiley:
